// client/src/components/navbar.vue
<script lang="ts" setup>
import useAuthStore from '@/lib/store'
import api from '@/lib/api'
import { useRouter } from 'vue-router'
import { computed } from 'vue'
import { useDark } from '@vueuse/core'

import { Button } from '@/components/ui/button'
import { MoonIcon, SunIcon, LogOut } from 'lucide-vue-next'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from '@/components/ui/dropdown-menu'
import { toast } from 'vue-sonner'

const store = useAuthStore()
const user = computed(() => store.user)
const isAuthenticated = computed(() => store.isAuthenticated)
const router = useRouter()
const isDark = useDark()

const handleLogout = async () => {
  try {
    await api.post('/api/auth/signout')
    localStorage.removeItem('accessToken')
    store.setUser(null)
    store.setIsAuthenticated(false)
    router.push('/')
  } catch (error: any) {
    if (error.response.status === 400) toast.error(error.response.data.error)
    else toast.error('Internal server error')
  }
}
</script>

<template>
  <div class="flex justify-center">
    <div class="flex items-center justify-between w-full max-w-[800px]">
      <RouterLink to="/" class="text-2xl font-bold"> Revite </RouterLink>
      <div class="flex items-center gap-4">
        <DropdownMenu v-if="isAuthenticated">
          <DropdownMenuTrigger as-child>
            <Button>{{ user?.name }}</Button>
          </DropdownMenuTrigger>
          <DropdownMenuContent>
            <DropdownMenuItem @click="handleLogout">
              <LogOut />
              Sign out
            </DropdownMenuItem>
          </DropdownMenuContent>
        </DropdownMenu>
        <Button v-else @click="router.push('/signin')"> Sign in </Button>
        <MoonIcon v-if="isDark" @click="isDark = false" />
        <SunIcon v-else @click="isDark = true" />
      </div>
    </div>
  </div>
</template>

// src/components/navbar.tsx
import { toast } from 'sonner'
import { SunIcon, MoonIcon, LogOut } from 'lucide-react'
import useAuthStore from '@/lib/store'
import api from '@/lib/api'
import useTheme from '@/hooks/use-theme'
import { Button } from './ui/button'
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger } from './ui/dropdown-menu'
import { navigate } from 'vike/client/router'

const Navbar: React.FC = () => {
  const { user, isAuthenticated, setUser } = useAuthStore()
  const { theme, setTheme } = useTheme()

  const handleLogout = async () => {
    try {
      await api.post('/api/auth/signout')
      localStorage.removeItem('accessToken')
      setUser(null)
      navigate('/')
    } catch (error: any) {
      toast.error(error.response.data.error)
    }
  }

  return (
    <div className='flex justify-center'>
      <div className='flex items-center justify-between w-full max-w-[800px]'>
        <a href='/' className='text-2xl font-bold'>
          Revite
        </a>

        <div className='flex items-center gap-4'>
          {isAuthenticated ? (
            <DropdownMenu>
              <DropdownMenuTrigger asChild>
                <Button variant='outline'>{user?.name}</Button>
              </DropdownMenuTrigger>
              <DropdownMenuContent>
                <DropdownMenuItem>
                  <LogOut />
                  <span onClick={handleLogout}>Sign out</span>
                </DropdownMenuItem>
              </DropdownMenuContent>
            </DropdownMenu>
          ) : (
            <>
              <Button variant='outline'>
                <a href='/signup'>Sign up</a>
              </Button>
            </>
          )}
          <Button onClick={() => setTheme(theme === 'light' ? 'dark' : 'light')} variant='outline' size='icon'>
            {theme === 'light' ? <SunIcon /> : <MoonIcon />}
          </Button>
        </div>
      </div>
    </div>
  )
}

export default Navbar
